## mysql
# CalendarEvent
CREATE TABLE DB_TABLE_PREFIXCalendarEvent(
 DB_COLUMN_PREFIXid int(11) NOT NULL,
 DB_COLUMN_PREFIXstart int(11),
 DB_COLUMN_PREFIXend int(11),
 DB_COLUMN_PREFIXsummary varchar(255),
 PRIMARY KEY(DB_COLUMN_PREFIXid)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CalendarEvent', 0, 1);

## postgres
# CalendarEvent
CREATE TABLE DB_TABLE_PREFIXCalendarEvent(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXstart INTEGER,
 DB_COLUMN_PREFIXend INTEGER,
 DB_COLUMN_PREFIXsummary VARCHAR(255)
);

ALTER TABLE DB_TABLE_PREFIXCalendarEvent ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CalendarEvent', 0, 1);

## oracle
# CalendarEvent
CREATE TABLE DB_TABLE_PREFIXCalendarEvent(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXstart INTEGER,
 DB_COLUMN_PREFIXend INTEGER,
 DB_COLUMN_PREFIXsummary VARCHAR2(255)
);

ALTER TABLE DB_TABLE_PREFIXCalendarEvent
 ADD PRIMARY KEY (DB_COLUMN_PREFIXid)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CalendarEvent', 0, 1);

## db2
# CalendarEvent
CREATE TABLE DB_TABLE_PREFIXCalendarEvent(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXstart INTEGER,
 DB_COLUMN_PREFIXend INTEGER,
 DB_COLUMN_PREFIXsummary VARCHAR(255)
);

ALTER TABLE DB_TABLE_PREFIXCalendarEvent ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CalendarEvent', 0, 1);

## mssql
# CalendarEvent
CREATE TABLE DB_TABLE_PREFIXCalendarEvent(
 DB_COLUMN_PREFIXid INT NOT NULL,
 DB_COLUMN_PREFIXstart INT NULL,
 DB_COLUMN_PREFIXend INT NULL,
 DB_COLUMN_PREFIXsummary NVARCHAR(255) NULL
);

ALTER TABLE DB_TABLE_PREFIXCalendarEvent ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CalendarEvent', 0, 1);

