<?php

// $Id: frame.inc 1102 2007-06-12 18:30:45Z mindless $
$frameData = array(
	'name'      => $gallery->i18n('X_White Shadow - 14px (png)'),
	// Top Left
	'imageTL'   => 'TL.png',
	'widthTL'   => 43,
	'heightTL'  => 43,
	// Top
	'imageTTL'  => '',
	'widthTTL'  => 0,
	'imageTT'   => 'TT.png',
	'heightTT'  => 43,
	'imageTTR'  => '',
	'widthTTR'  => 0,
	// Top Right
	'imageTR'   => 'TR.png',
	'widthTR'   => 43,
	'heightTR'  => 43,
	// Left
	'imageLLT'  => '',
	'heightLLT' => 0,
	'imageLL'   => 'LL.png',
	'widthLL'   => 43,
	'imageLLB'  => '',
	'heightLLB' => 0,
	// Right
	'imageRRT'  => '',
	'heightRRT' => 0,
	'imageRR'   => 'RR.png',
	'widthRR'   => 43,
	'imageRRB'  => '',
	'heightRRB' => 0,
	// Bottom Left
	'imageBL'   => 'BL.png',
	'widthBL'   => 43,
	'heightBL'  => 43,
	// Bottom
	'imageBBL'  => '',
	'widthBBL'  => 0,
	'imageBB'   => 'BB.png',
	'heightBB'  => 43,
	'imageBBR'  => '',
	'widthBBR'  => 0,
	// Bottom Right
	'imageBR'   => 'BR.png',
	'widthBR'   => 43,
	'heightBR'  => 43,
);
