## mysql
# A_CheckoutDiscountMap_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutDiscountMap
  ADD COLUMN DB_COLUMN_PREFIXgroupId int(11);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutDiscountMap' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutDiscountMap_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutDiscountMap
  ADD COLUMN DB_COLUMN_PREFIXgroupId int(11);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutDiscountMap' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutItem_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutItem
  MODIFY COLUMN DB_COLUMN_PREFIXqty int(11);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutItem_1.1
ALTER TABLE DB_TABLE_PREFIXCheckoutItem
  ADD COLUMN DB_COLUMN_PREFIXtransaction int(11);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=2
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=1;

# A_GalleryCheckoutItem_1.2
ALTER TABLE DB_TABLE_PREFIXCheckoutItem
  ADD COLUMN DB_COLUMN_PREFIXitemText varchar(128);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=3
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=2;

# A_GalleryCheckoutTransaction_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP COLUMN DB_COLUMN_PREFIXppId,
  DROP COLUMN DB_COLUMN_PREFIXppStatus,
  DROP COLUMN DB_COLUMN_PREFIXppDate,
  DROP COLUMN DB_COLUMN_PREFIXppSign,
  DROP COLUMN DB_COLUMN_PREFIXppFirstName,
  DROP COLUMN DB_COLUMN_PREFIXppLastName,
  DROP COLUMN DB_COLUMN_PREFIXppEmail,
  DROP COLUMN DB_COLUMN_PREFIXnotes,
  ADD COLUMN DB_COLUMN_PREFIXfirstName varchar(128),
  ADD COLUMN DB_COLUMN_PREFIXlastName varchar(128),
  ADD COLUMN DB_COLUMN_PREFIXemail varchar(128),
  ADD COLUMN DB_COLUMN_PREFIXrecipientName varchar(128),
  ADD COLUMN DB_COLUMN_PREFIXaddress1 varchar(128),
  ADD COLUMN DB_COLUMN_PREFIXaddress2 varchar(128),
  ADD COLUMN DB_COLUMN_PREFIXaddress3 varchar(128),
  ADD COLUMN DB_COLUMN_PREFIXaddress4 varchar(128),
  ADD COLUMN DB_COLUMN_PREFIXaddress5 varchar(128),
  ADD COLUMN DB_COLUMN_PREFIXaddressZip varchar(128),
  ADD COLUMN DB_COLUMN_PREFIXaddressCountry varchar(128),
  ADD COLUMN DB_COLUMN_PREFIXcustNotes text;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutTransaction_1.1
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  MODIFY COLUMN DB_COLUMN_PREFIXamount varchar(32),
  ADD COLUMN DB_COLUMN_PREFIXpostage varchar(32);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=2
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=1;

# A_GalleryCheckoutTransaction_1.10
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD COLUMN DB_COLUMN_PREFIXlanguageCode varchar(32);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=11
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=10;

# A_GalleryCheckoutTransaction_1.11
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD COLUMN DB_COLUMN_PREFIXtelephone varchar(128);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=12
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=11;

# A_GalleryCheckoutTransaction_1.12
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD COLUMN DB_COLUMN_PREFIXflagConfirmed int(1);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=13
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=12;

# A_GalleryCheckoutTransaction_1.13
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD COLUMN DB_COLUMN_PREFIXtimeConfirmed int(11) NOT NULL DEFAULT '0',
  ADD COLUMN DB_COLUMN_PREFIXtimePaid int(11) NOT NULL DEFAULT '0',
  ADD COLUMN DB_COLUMN_PREFIXtimeCleared int(11) NOT NULL DEFAULT '0',
  ADD COLUMN DB_COLUMN_PREFIXtimeFulfil int(11) NOT NULL DEFAULT '0',
  ADD COLUMN DB_COLUMN_PREFIXtimeFulfilled int(11) NOT NULL DEFAULT '0',
  ADD COLUMN DB_COLUMN_PREFIXtimeCompleted int(11) NOT NULL DEFAULT '0',
  ADD COLUMN DB_COLUMN_PREFIXtimeHold int(11) NOT NULL DEFAULT '0',
  ADD COLUMN DB_COLUMN_PREFIXtimeProblem int(11) NOT NULL DEFAULT '0',
  ADD COLUMN DB_COLUMN_PREFIXtimeDownloaded int(11) NOT NULL DEFAULT '0';

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=14
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=13;

# A_GalleryCheckoutTransaction_1.14
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP COLUMN DB_COLUMN_PREFIXflagConfirmed,
  DROP COLUMN DB_COLUMN_PREFIXflagPaid,
  DROP COLUMN DB_COLUMN_PREFIXflagCleared,
  DROP COLUMN DB_COLUMN_PREFIXflagFulfil,
  DROP COLUMN DB_COLUMN_PREFIXflagFulfilled,
  DROP COLUMN DB_COLUMN_PREFIXflagCompleted,
  DROP COLUMN DB_COLUMN_PREFIXflagHold,
  DROP COLUMN DB_COLUMN_PREFIXflagProblem,
  DROP COLUMN DB_COLUMN_PREFIXflagDownloaded;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=15
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=14;

# A_GalleryCheckoutTransaction_1.2
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD COLUMN DB_COLUMN_PREFIXpaymentPlugin varchar(128),
  ADD COLUMN DB_COLUMN_PREFIXflagPaid int(1),
  ADD COLUMN DB_COLUMN_PREFIXflagCleared int(1);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=3
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=2;

# A_GalleryCheckoutTransaction_1.3
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD COLUMN DB_COLUMN_PREFIXflagFulfil int(1),
  ADD COLUMN DB_COLUMN_PREFIXflagFulfilled int(1),
  ADD COLUMN DB_COLUMN_PREFIXflagCompleted int(1),
  ADD COLUMN DB_COLUMN_PREFIXflagHold int(1),
  ADD COLUMN DB_COLUMN_PREFIXflagProblem int(1);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=4
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=3;

# A_GalleryCheckoutTransaction_1.4
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD COLUMN DB_COLUMN_PREFIXflagDownloaded int(1);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=5
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=4;

# A_GalleryCheckoutTransaction_1.5
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD COLUMN DB_COLUMN_PREFIXdownloadAttempts int(11);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=6
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=5;

# A_GalleryCheckoutTransaction_1.6
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD COLUMN DB_COLUMN_PREFIXcustComments text;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=7
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=6;

# A_GalleryCheckoutTransaction_1.7
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD COLUMN DB_COLUMN_PREFIXpostageType varchar(128);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=8
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=7;

# A_GalleryCheckoutTransaction_1.8
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD COLUMN DB_COLUMN_PREFIXsecurity varchar(32) NOT NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=9
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=8;

# A_GalleryCheckoutTransaction_1.9
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD COLUMN DB_COLUMN_PREFIXdiscount varchar(32),
  ADD COLUMN DB_COLUMN_PREFIXdiscountDescription varchar(128);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=10
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=9;

# CheckoutDiscountMap
CREATE TABLE DB_TABLE_PREFIXCheckoutDiscountMap(
 DB_COLUMN_PREFIXdiscountId int(11) NOT NULL,
 DB_COLUMN_PREFIXdescription varchar(128),
 DB_COLUMN_PREFIXentryCode varchar(32),
 DB_COLUMN_PREFIXminValue varchar(32),
 DB_COLUMN_PREFIXminItems int(11),
 DB_COLUMN_PREFIXminProducts int(11),
 DB_COLUMN_PREFIXgroupId int(11),
 DB_COLUMN_PREFIXdiscountPercent varchar(32),
 DB_COLUMN_PREFIXdiscountFixed varchar(32),
 DB_COLUMN_PREFIXfreePostage int(1),
 DB_COLUMN_PREFIXapplyDefault int(1),
 DB_COLUMN_PREFIXpriority int(11),
 INDEX DB_TABLE_PREFIXCheckoutDiscountMap_6217(DB_COLUMN_PREFIXdiscountId)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutDiscountMap', 1, 1);

# CheckoutProductMap
CREATE TABLE DB_TABLE_PREFIXCheckoutProductMap(
 DB_COLUMN_PREFIXproductId int(11) NOT NULL,
 DB_COLUMN_PREFIXparamName varchar(128) NOT NULL,
 DB_COLUMN_PREFIXparamValue text NOT NULL,
 DB_COLUMN_PREFIXownerId int(11) NOT NULL,
 INDEX DB_TABLE_PREFIXCheckoutProductMap_37925(DB_COLUMN_PREFIXproductId),
 INDEX DB_TABLE_PREFIXCheckoutProductMap_21573(DB_COLUMN_PREFIXownerId)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutProductMap', 1, 0);

# GalleryCheckoutItem
CREATE TABLE DB_TABLE_PREFIXCheckoutItem(
 DB_COLUMN_PREFIXid int(11) NOT NULL,
 DB_COLUMN_PREFIXitem int(11) NOT NULL,
 DB_COLUMN_PREFIXtransaction int(11) NOT NULL,
 DB_COLUMN_PREFIXitemName varchar(128),
 DB_COLUMN_PREFIXitemText varchar(128),
 DB_COLUMN_PREFIXproduct int(11) NOT NULL,
 DB_COLUMN_PREFIXproductName varchar(128),
 DB_COLUMN_PREFIXqty int(11) NOT NULL,
 DB_COLUMN_PREFIXpriceEach varchar(32),
 DB_COLUMN_PREFIXpriceTotal varchar(32),
 DB_COLUMN_PREFIXnotes text,
 PRIMARY KEY(DB_COLUMN_PREFIXid),
 INDEX DB_TABLE_PREFIXCheckoutItem_72670(DB_COLUMN_PREFIXitem),
 INDEX DB_TABLE_PREFIXCheckoutItem_8593(DB_COLUMN_PREFIXtransaction)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutItem', 1, 3);

# GalleryCheckoutTransaction
CREATE TABLE DB_TABLE_PREFIXCheckoutTransaction(
 DB_COLUMN_PREFIXid int(11) NOT NULL,
 DB_COLUMN_PREFIXdate int(11) NOT NULL,
 DB_COLUMN_PREFIXsecurity varchar(32) NOT NULL,
 DB_COLUMN_PREFIXbuyerId int(11) NOT NULL,
 DB_COLUMN_PREFIXhost varchar(128) NOT NULL,
 DB_COLUMN_PREFIXlanguageCode varchar(32),
 DB_COLUMN_PREFIXpostage varchar(32),
 DB_COLUMN_PREFIXpostageType varchar(128),
 DB_COLUMN_PREFIXdiscount varchar(32),
 DB_COLUMN_PREFIXdiscountDescription varchar(128),
 DB_COLUMN_PREFIXamount varchar(32),
 DB_COLUMN_PREFIXfirstName varchar(128),
 DB_COLUMN_PREFIXlastName varchar(128),
 DB_COLUMN_PREFIXemail varchar(128),
 DB_COLUMN_PREFIXrecipientName varchar(128),
 DB_COLUMN_PREFIXtelephone varchar(128),
 DB_COLUMN_PREFIXaddress1 varchar(128),
 DB_COLUMN_PREFIXaddress2 varchar(128),
 DB_COLUMN_PREFIXaddress3 varchar(128),
 DB_COLUMN_PREFIXaddress4 varchar(128),
 DB_COLUMN_PREFIXaddress5 varchar(128),
 DB_COLUMN_PREFIXaddressZip varchar(128),
 DB_COLUMN_PREFIXaddressCountry varchar(128),
 DB_COLUMN_PREFIXcustNotes text,
 DB_COLUMN_PREFIXcustComments text,
 DB_COLUMN_PREFIXpaymentPlugin varchar(128),
 DB_COLUMN_PREFIXtimeConfirmed int(11) NOT NULL,
 DB_COLUMN_PREFIXtimePaid int(11) NOT NULL,
 DB_COLUMN_PREFIXtimeCleared int(11) NOT NULL,
 DB_COLUMN_PREFIXtimeFulfil int(11) NOT NULL,
 DB_COLUMN_PREFIXtimeFulfilled int(11) NOT NULL,
 DB_COLUMN_PREFIXtimeCompleted int(11) NOT NULL,
 DB_COLUMN_PREFIXtimeHold int(11) NOT NULL,
 DB_COLUMN_PREFIXtimeProblem int(11) NOT NULL,
 DB_COLUMN_PREFIXtimeDownloaded int(11) NOT NULL,
 DB_COLUMN_PREFIXdownloadAttempts int(11) NOT NULL,
 PRIMARY KEY(DB_COLUMN_PREFIXid),
 INDEX DB_TABLE_PREFIXCheckoutTransaction_95610(DB_COLUMN_PREFIXdate)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutTransaction', 1, 15);

## postgres
# A_CheckoutDiscountMap_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutDiscountMap ADD COLUMN DB_COLUMN_PREFIXgroupId INTEGER;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutDiscountMap' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutDiscountMap_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutDiscountMap ADD COLUMN DB_COLUMN_PREFIXgroupId INTEGER;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutDiscountMap' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutItem_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD COLUMN DB_COLUMN_PREFIXqtyTemp INTEGER;

UPDATE DB_TABLE_PREFIXCheckoutItem SET DB_COLUMN_PREFIXqtyTemp = CAST(DB_COLUMN_PREFIXqty AS INTEGER);

ALTER TABLE DB_TABLE_PREFIXCheckoutItem DROP DB_COLUMN_PREFIXqty;

ALTER TABLE DB_TABLE_PREFIXCheckoutItem RENAME DB_COLUMN_PREFIXqtyTemp to DB_COLUMN_PREFIXqty;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutItem_1.1
ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD COLUMN DB_COLUMN_PREFIXtransaction INTEGER;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=2
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=1;

# A_GalleryCheckoutItem_1.2
ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD COLUMN DB_COLUMN_PREFIXitemText VARCHAR(128);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=3
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=2;

# A_GalleryCheckoutTransaction_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppId;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppStatus;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppDate;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppSign;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppFirstName;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppLastName;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppEmail;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXnotes;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXfirstName VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXlastName VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXemail VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXrecipientName VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXaddress1 VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXaddress2 VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXaddress3 VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXaddress4 VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXaddress5 VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXaddressZip VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXaddressCountry VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXcustNotes text;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutTransaction_1.1
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXamountTemp VARCHAR(32);

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXamountTemp = CAST(DB_COLUMN_PREFIXamount AS VARCHAR(32));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP DB_COLUMN_PREFIXamount;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction RENAME DB_COLUMN_PREFIXamountTemp to DB_COLUMN_PREFIXamount;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXpostage VARCHAR(32);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=2
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=1;

# A_GalleryCheckoutTransaction_1.10
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXlanguageCode VARCHAR(32);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=11
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=10;

# A_GalleryCheckoutTransaction_1.11
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtelephone VARCHAR(128);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=12
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=11;

# A_GalleryCheckoutTransaction_1.12
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagConfirmed SMALLINT;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=13
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=12;

# A_GalleryCheckoutTransaction_1.13
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeConfirmed INTEGER;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER COLUMN DB_COLUMN_PREFIXtimeConfirmed SET DEFAULT '0';

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXtimeConfirmed = '0';

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER DB_COLUMN_PREFIXtimeConfirmed SET NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimePaid INTEGER;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER COLUMN DB_COLUMN_PREFIXtimePaid SET DEFAULT '0';

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXtimePaid = '0';

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER DB_COLUMN_PREFIXtimePaid SET NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeCleared INTEGER;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER COLUMN DB_COLUMN_PREFIXtimeCleared SET DEFAULT '0';

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXtimeCleared = '0';

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER DB_COLUMN_PREFIXtimeCleared SET NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeFulfil INTEGER;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER COLUMN DB_COLUMN_PREFIXtimeFulfil SET DEFAULT '0';

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXtimeFulfil = '0';

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER DB_COLUMN_PREFIXtimeFulfil SET NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeFulfilled INTEGER;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER COLUMN DB_COLUMN_PREFIXtimeFulfilled SET DEFAULT '0';

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXtimeFulfilled = '0';

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER DB_COLUMN_PREFIXtimeFulfilled SET NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeCompleted INTEGER;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER COLUMN DB_COLUMN_PREFIXtimeCompleted SET DEFAULT '0';

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXtimeCompleted = '0';

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER DB_COLUMN_PREFIXtimeCompleted SET NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeHold INTEGER;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER COLUMN DB_COLUMN_PREFIXtimeHold SET DEFAULT '0';

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXtimeHold = '0';

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER DB_COLUMN_PREFIXtimeHold SET NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeProblem INTEGER;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER COLUMN DB_COLUMN_PREFIXtimeProblem SET DEFAULT '0';

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXtimeProblem = '0';

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER DB_COLUMN_PREFIXtimeProblem SET NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeDownloaded INTEGER;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER COLUMN DB_COLUMN_PREFIXtimeDownloaded SET DEFAULT '0';

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXtimeDownloaded = '0';

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER DB_COLUMN_PREFIXtimeDownloaded SET NOT NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=14
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=13;

# A_GalleryCheckoutTransaction_1.14
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagConfirmed;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagPaid;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagCleared;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagFulfil;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagFulfilled;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagCompleted;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagHold;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagProblem;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagDownloaded;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=15
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=14;

# A_GalleryCheckoutTransaction_1.2
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXpaymentPlugin VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagPaid SMALLINT;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagCleared SMALLINT;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=3
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=2;

# A_GalleryCheckoutTransaction_1.3
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagFulfil SMALLINT;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagFulfilled SMALLINT;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagCompleted SMALLINT;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagHold SMALLINT;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagProblem SMALLINT;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=4
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=3;

# A_GalleryCheckoutTransaction_1.4
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagDownloaded SMALLINT;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=5
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=4;

# A_GalleryCheckoutTransaction_1.5
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXdownloadAttempts INTEGER;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=6
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=5;

# A_GalleryCheckoutTransaction_1.6
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXcustComments text;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=7
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=6;

# A_GalleryCheckoutTransaction_1.7
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXpostageType VARCHAR(128);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=8
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=7;

# A_GalleryCheckoutTransaction_1.8
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXsecurity VARCHAR(32);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ALTER DB_COLUMN_PREFIXsecurity SET NOT NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=9
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=8;

# A_GalleryCheckoutTransaction_1.9
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXdiscount VARCHAR(32);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXdiscountDescription VARCHAR(128);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=10
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=9;

# CheckoutDiscountMap
CREATE TABLE DB_TABLE_PREFIXCheckoutDiscountMap(
 DB_COLUMN_PREFIXdiscountId INTEGER NOT NULL,
 DB_COLUMN_PREFIXdescription VARCHAR(128),
 DB_COLUMN_PREFIXentryCode VARCHAR(32),
 DB_COLUMN_PREFIXminValue VARCHAR(32),
 DB_COLUMN_PREFIXminItems INTEGER,
 DB_COLUMN_PREFIXminProducts INTEGER,
 DB_COLUMN_PREFIXgroupId INTEGER,
 DB_COLUMN_PREFIXdiscountPercent VARCHAR(32),
 DB_COLUMN_PREFIXdiscountFixed VARCHAR(32),
 DB_COLUMN_PREFIXfreePostage SMALLINT,
 DB_COLUMN_PREFIXapplyDefault SMALLINT,
 DB_COLUMN_PREFIXpriority INTEGER
);

CREATE INDEX DB_TABLE_PREFIXCheckoutDiscountMap_6217 ON DB_TABLE_PREFIXCheckoutDiscountMap(DB_COLUMN_PREFIXdiscountId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutDiscountMap', 1, 1);

# CheckoutProductMap
CREATE TABLE DB_TABLE_PREFIXCheckoutProductMap(
 DB_COLUMN_PREFIXproductId INTEGER NOT NULL,
 DB_COLUMN_PREFIXparamName VARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXparamValue text NOT NULL,
 DB_COLUMN_PREFIXownerId INTEGER NOT NULL
);

CREATE INDEX DB_TABLE_PREFIXCheckoutProductMap_37925 ON DB_TABLE_PREFIXCheckoutProductMap(DB_COLUMN_PREFIXproductId);

CREATE INDEX DB_TABLE_PREFIXCheckoutProductMap_21573 ON DB_TABLE_PREFIXCheckoutProductMap(DB_COLUMN_PREFIXownerId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutProductMap', 1, 0);

# GalleryCheckoutItem
CREATE TABLE DB_TABLE_PREFIXCheckoutItem(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXitem INTEGER NOT NULL,
 DB_COLUMN_PREFIXtransaction INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemName VARCHAR(128),
 DB_COLUMN_PREFIXitemText VARCHAR(128),
 DB_COLUMN_PREFIXproduct INTEGER NOT NULL,
 DB_COLUMN_PREFIXproductName VARCHAR(128),
 DB_COLUMN_PREFIXqty INTEGER NOT NULL,
 DB_COLUMN_PREFIXpriceEach VARCHAR(32),
 DB_COLUMN_PREFIXpriceTotal VARCHAR(32),
 DB_COLUMN_PREFIXnotes text
);

ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

CREATE INDEX DB_TABLE_PREFIXCheckoutItem_72670 ON DB_TABLE_PREFIXCheckoutItem(DB_COLUMN_PREFIXitem);

CREATE INDEX DB_TABLE_PREFIXCheckoutItem_8593 ON DB_TABLE_PREFIXCheckoutItem(DB_COLUMN_PREFIXtransaction);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutItem', 1, 3);

# GalleryCheckoutTransaction
CREATE TABLE DB_TABLE_PREFIXCheckoutTransaction(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXdate INTEGER NOT NULL,
 DB_COLUMN_PREFIXsecurity VARCHAR(32) NOT NULL,
 DB_COLUMN_PREFIXbuyerId INTEGER NOT NULL,
 DB_COLUMN_PREFIXhost VARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXlanguageCode VARCHAR(32),
 DB_COLUMN_PREFIXpostage VARCHAR(32),
 DB_COLUMN_PREFIXpostageType VARCHAR(128),
 DB_COLUMN_PREFIXdiscount VARCHAR(32),
 DB_COLUMN_PREFIXdiscountDescription VARCHAR(128),
 DB_COLUMN_PREFIXamount VARCHAR(32),
 DB_COLUMN_PREFIXfirstName VARCHAR(128),
 DB_COLUMN_PREFIXlastName VARCHAR(128),
 DB_COLUMN_PREFIXemail VARCHAR(128),
 DB_COLUMN_PREFIXrecipientName VARCHAR(128),
 DB_COLUMN_PREFIXtelephone VARCHAR(128),
 DB_COLUMN_PREFIXaddress1 VARCHAR(128),
 DB_COLUMN_PREFIXaddress2 VARCHAR(128),
 DB_COLUMN_PREFIXaddress3 VARCHAR(128),
 DB_COLUMN_PREFIXaddress4 VARCHAR(128),
 DB_COLUMN_PREFIXaddress5 VARCHAR(128),
 DB_COLUMN_PREFIXaddressZip VARCHAR(128),
 DB_COLUMN_PREFIXaddressCountry VARCHAR(128),
 DB_COLUMN_PREFIXcustNotes text,
 DB_COLUMN_PREFIXcustComments text,
 DB_COLUMN_PREFIXpaymentPlugin VARCHAR(128),
 DB_COLUMN_PREFIXtimeConfirmed INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimePaid INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeCleared INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeFulfil INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeFulfilled INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeCompleted INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeHold INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeProblem INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeDownloaded INTEGER NOT NULL,
 DB_COLUMN_PREFIXdownloadAttempts INTEGER NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

CREATE INDEX DB_TABLE_PREFIXCheckoutTransaction_95610 ON DB_TABLE_PREFIXCheckoutTransaction(DB_COLUMN_PREFIXdate);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutTransaction', 1, 15);

## oracle
# A_CheckoutDiscountMap_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutDiscountMap
  ADD (DB_COLUMN_PREFIXgroupId INTEGER);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutDiscountMap' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutDiscountMap_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutDiscountMap
  ADD (DB_COLUMN_PREFIXgroupId INTEGER);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutDiscountMap' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutItem_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD (DB_COLUMN_PREFIXqtyTemp INTEGER);

UPDATE DB_TABLE_PREFIXCheckoutItem SET DB_COLUMN_PREFIXqtyTemp = DB_COLUMN_PREFIXqty;

ALTER TABLE DB_TABLE_PREFIXCheckoutItem DROP (DB_COLUMN_PREFIXqty);

ALTER TABLE DB_TABLE_PREFIXCheckoutItem RENAME COLUMN DB_COLUMN_PREFIXqtyTemp TO DB_COLUMN_PREFIXqty;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutItem_1.1
ALTER TABLE DB_TABLE_PREFIXCheckoutItem
  ADD (DB_COLUMN_PREFIXtransaction INTEGER);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=2
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=1;

# A_GalleryCheckoutItem_1.2
ALTER TABLE DB_TABLE_PREFIXCheckoutItem
  ADD (DB_COLUMN_PREFIXitemText VARCHAR2(128));

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=3
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=2;

# A_GalleryCheckoutTransaction_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXppId);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXppStatus);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXppDate);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXppSign);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXppFirstName);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXppLastName);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXppEmail);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXnotes);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXfirstName VARCHAR2(128));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXlastName VARCHAR2(128));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXemail VARCHAR2(128));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXrecipientName VARCHAR2(128));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXaddress1 VARCHAR2(128));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXaddress2 VARCHAR2(128));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXaddress3 VARCHAR2(128));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXaddress4 VARCHAR2(128));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXaddress5 VARCHAR2(128));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXaddressZip VARCHAR2(128));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXaddressCountry VARCHAR2(128));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXcustNotes CLOB);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutTransaction_1.1
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD (DB_COLUMN_PREFIXamountTemp VARCHAR2(32));

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXamountTemp = DB_COLUMN_PREFIXamount;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP (DB_COLUMN_PREFIXamount);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction RENAME COLUMN DB_COLUMN_PREFIXamountTemp TO DB_COLUMN_PREFIXamount;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXpostage VARCHAR2(32));

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=2
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=1;

# A_GalleryCheckoutTransaction_1.10
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXlanguageCode VARCHAR2(32));

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=11
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=10;

# A_GalleryCheckoutTransaction_1.11
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXtelephone VARCHAR2(128));

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=12
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=11;

# A_GalleryCheckoutTransaction_1.12
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXflagConfirmed NUMBER(1));

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=13
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=12;

# A_GalleryCheckoutTransaction_1.13
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXtimeConfirmed INTEGER DEFAULT '0' NOT NULL);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXtimePaid INTEGER DEFAULT '0' NOT NULL);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXtimeCleared INTEGER DEFAULT '0' NOT NULL);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXtimeFulfil INTEGER DEFAULT '0' NOT NULL);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXtimeFulfilled INTEGER DEFAULT '0' NOT NULL);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXtimeCompleted INTEGER DEFAULT '0' NOT NULL);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXtimeHold INTEGER DEFAULT '0' NOT NULL);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXtimeProblem INTEGER DEFAULT '0' NOT NULL);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXtimeDownloaded INTEGER DEFAULT '0' NOT NULL);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=14
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=13;

# A_GalleryCheckoutTransaction_1.14
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXflagConfirmed);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXflagPaid);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXflagCleared);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXflagFulfil);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXflagFulfilled);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXflagCompleted);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXflagHold);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXflagProblem);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  DROP (DB_COLUMN_PREFIXflagDownloaded);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=15
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=14;

# A_GalleryCheckoutTransaction_1.2
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXpaymentPlugin VARCHAR2(128));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXflagPaid NUMBER(1));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXflagCleared NUMBER(1));

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=3
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=2;

# A_GalleryCheckoutTransaction_1.3
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXflagFulfil NUMBER(1));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXflagFulfilled NUMBER(1));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXflagCompleted NUMBER(1));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXflagHold NUMBER(1));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXflagProblem NUMBER(1));

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=4
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=3;

# A_GalleryCheckoutTransaction_1.4
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXflagDownloaded NUMBER(1));

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=5
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=4;

# A_GalleryCheckoutTransaction_1.5
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXdownloadAttempts INTEGER);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=6
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=5;

# A_GalleryCheckoutTransaction_1.6
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXcustComments CLOB);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=7
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=6;

# A_GalleryCheckoutTransaction_1.7
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXpostageType VARCHAR2(128));

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=8
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=7;

# A_GalleryCheckoutTransaction_1.8
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXsecurity VARCHAR2(32) NOT NULL);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=9
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=8;

# A_GalleryCheckoutTransaction_1.9
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXdiscount VARCHAR2(32));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
  ADD (DB_COLUMN_PREFIXdiscountDescription VARCHAR2(128));

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=10
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=9;

# CheckoutDiscountMap
CREATE TABLE DB_TABLE_PREFIXCheckoutDiscountMap(
 DB_COLUMN_PREFIXdiscountId INTEGER NOT NULL,
 DB_COLUMN_PREFIXdescription VARCHAR2(128),
 DB_COLUMN_PREFIXentryCode VARCHAR2(32),
 DB_COLUMN_PREFIXminValue VARCHAR2(32),
 DB_COLUMN_PREFIXminItems INTEGER,
 DB_COLUMN_PREFIXminProducts INTEGER,
 DB_COLUMN_PREFIXgroupId INTEGER,
 DB_COLUMN_PREFIXdiscountPercent VARCHAR2(32),
 DB_COLUMN_PREFIXdiscountFixed VARCHAR2(32),
 DB_COLUMN_PREFIXfreePostage NUMBER(1),
 DB_COLUMN_PREFIXapplyDefault NUMBER(1),
 DB_COLUMN_PREFIXpriority INTEGER
);

CREATE INDEX DB_TABLE_PREFIXCheckoutDiscountMap_6217
   ON DB_TABLE_PREFIXCheckoutDiscountMap(DB_COLUMN_PREFIXdiscountId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutDiscountMap', 1, 1);

# CheckoutProductMap
CREATE TABLE DB_TABLE_PREFIXCheckoutProductMap(
 DB_COLUMN_PREFIXproductId INTEGER NOT NULL,
 DB_COLUMN_PREFIXparamName VARCHAR2(128) NOT NULL,
 DB_COLUMN_PREFIXparamValue VARCHAR2(4000) NOT NULL,
 DB_COLUMN_PREFIXownerId INTEGER NOT NULL
);

CREATE INDEX DB_TABLE_PREFIXCheckoutProductMap_37925
   ON DB_TABLE_PREFIXCheckoutProductMap(DB_COLUMN_PREFIXproductId);

CREATE INDEX DB_TABLE_PREFIXCheckoutProductMap_21573
   ON DB_TABLE_PREFIXCheckoutProductMap(DB_COLUMN_PREFIXownerId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutProductMap', 1, 0);

# GalleryCheckoutItem
CREATE TABLE DB_TABLE_PREFIXCheckoutItem(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXitem INTEGER NOT NULL,
 DB_COLUMN_PREFIXtransaction INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemName VARCHAR2(128),
 DB_COLUMN_PREFIXitemText VARCHAR2(128),
 DB_COLUMN_PREFIXproduct INTEGER NOT NULL,
 DB_COLUMN_PREFIXproductName VARCHAR2(128),
 DB_COLUMN_PREFIXqty INTEGER NOT NULL,
 DB_COLUMN_PREFIXpriceEach VARCHAR2(32),
 DB_COLUMN_PREFIXpriceTotal VARCHAR2(32),
 DB_COLUMN_PREFIXnotes CLOB
);

CREATE INDEX DB_TABLE_PREFIXCheckoutItem_72670
   ON DB_TABLE_PREFIXCheckoutItem(DB_COLUMN_PREFIXitem);

CREATE INDEX DB_TABLE_PREFIXCheckoutItem_8593
   ON DB_TABLE_PREFIXCheckoutItem(DB_COLUMN_PREFIXtransaction);

ALTER TABLE DB_TABLE_PREFIXCheckoutItem
 ADD PRIMARY KEY (DB_COLUMN_PREFIXid)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutItem', 1, 3);

# GalleryCheckoutTransaction
CREATE TABLE DB_TABLE_PREFIXCheckoutTransaction(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXdate INTEGER NOT NULL,
 DB_COLUMN_PREFIXsecurity VARCHAR2(32) NOT NULL,
 DB_COLUMN_PREFIXbuyerId INTEGER NOT NULL,
 DB_COLUMN_PREFIXhost VARCHAR2(128) NOT NULL,
 DB_COLUMN_PREFIXlanguageCode VARCHAR2(32),
 DB_COLUMN_PREFIXpostage VARCHAR2(32),
 DB_COLUMN_PREFIXpostageType VARCHAR2(128),
 DB_COLUMN_PREFIXdiscount VARCHAR2(32),
 DB_COLUMN_PREFIXdiscountDescription VARCHAR2(128),
 DB_COLUMN_PREFIXamount VARCHAR2(32),
 DB_COLUMN_PREFIXfirstName VARCHAR2(128),
 DB_COLUMN_PREFIXlastName VARCHAR2(128),
 DB_COLUMN_PREFIXemail VARCHAR2(128),
 DB_COLUMN_PREFIXrecipientName VARCHAR2(128),
 DB_COLUMN_PREFIXtelephone VARCHAR2(128),
 DB_COLUMN_PREFIXaddress1 VARCHAR2(128),
 DB_COLUMN_PREFIXaddress2 VARCHAR2(128),
 DB_COLUMN_PREFIXaddress3 VARCHAR2(128),
 DB_COLUMN_PREFIXaddress4 VARCHAR2(128),
 DB_COLUMN_PREFIXaddress5 VARCHAR2(128),
 DB_COLUMN_PREFIXaddressZip VARCHAR2(128),
 DB_COLUMN_PREFIXaddressCountry VARCHAR2(128),
 DB_COLUMN_PREFIXcustNotes CLOB,
 DB_COLUMN_PREFIXcustComments CLOB,
 DB_COLUMN_PREFIXpaymentPlugin VARCHAR2(128),
 DB_COLUMN_PREFIXtimeConfirmed INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimePaid INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeCleared INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeFulfil INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeFulfilled INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeCompleted INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeHold INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeProblem INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeDownloaded INTEGER NOT NULL,
 DB_COLUMN_PREFIXdownloadAttempts INTEGER NOT NULL
);

CREATE INDEX DB_TABLE_PREFIXCheckoutTransaction_95610
   ON DB_TABLE_PREFIXCheckoutTransaction(DB_COLUMN_PREFIXdate);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction
 ADD PRIMARY KEY (DB_COLUMN_PREFIXid)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutTransaction', 1, 15);

## db2
# A_CheckoutDiscountMap_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutDiscountMap ADD COLUMN DB_COLUMN_PREFIXgroupId INTEGER;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutDiscountMap' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutDiscountMap_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutDiscountMap ADD COLUMN DB_COLUMN_PREFIXgroupId INTEGER;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutDiscountMap' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutItem_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD COLUMN DB_COLUMN_PREFIXqtyTemp INTEGER;

UPDATE DB_TABLE_PREFIXCheckoutItem SET DB_COLUMN_PREFIXqtyTemp = CAST(DB_COLUMN_PREFIXqty AS INTEGER);

ALTER TABLE DB_TABLE_PREFIXCheckoutItem DROP COLUMN DB_COLUMN_PREFIXqty;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutItem');

ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD COLUMN DB_COLUMN_PREFIXqty INTEGER;

UPDATE DB_TABLE_PREFIXCheckoutItem SET DB_COLUMN_PREFIXqty = DB_COLUMN_PREFIXqtyTemp;

ALTER TABLE DB_TABLE_PREFIXCheckoutItem DROP COLUMN DB_COLUMN_PREFIXqtyTemp;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutItem');

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutItem_1.1
ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD COLUMN DB_COLUMN_PREFIXtransaction INTEGER;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=2
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=1;

# A_GalleryCheckoutItem_1.2
ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD COLUMN DB_COLUMN_PREFIXitemText VARCHAR(128);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=3
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=2;

# A_GalleryCheckoutTransaction_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppId;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppStatus;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppDate;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppSign;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppFirstName;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppLastName;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppEmail;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXnotes;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXfirstName VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXlastName VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXemail VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXrecipientName VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXaddress1 VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXaddress2 VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXaddress3 VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXaddress4 VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXaddress5 VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXaddressZip VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXaddressCountry VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXcustNotes VARCHAR(15000);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutTransaction_1.1
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXamountTemp VARCHAR(32);

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXamountTemp = CAST(DB_COLUMN_PREFIXamount AS VARCHAR(32));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXamount;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXamount VARCHAR(32);

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXamount = DB_COLUMN_PREFIXamountTemp;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXamountTemp;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXpostage VARCHAR(32);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=2
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=1;

# A_GalleryCheckoutTransaction_1.10
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXlanguageCode VARCHAR(32);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=11
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=10;

# A_GalleryCheckoutTransaction_1.11
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtelephone VARCHAR(128);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=12
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=11;

# A_GalleryCheckoutTransaction_1.12
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagConfirmed SMALLINT;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=13
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=12;

# A_GalleryCheckoutTransaction_1.13
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeConfirmed INTEGER NOT NULL DEFAULT 0;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimePaid INTEGER NOT NULL DEFAULT 0;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeCleared INTEGER NOT NULL DEFAULT 0;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeFulfil INTEGER NOT NULL DEFAULT 0;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeFulfilled INTEGER NOT NULL DEFAULT 0;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeCompleted INTEGER NOT NULL DEFAULT 0;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeHold INTEGER NOT NULL DEFAULT 0;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeProblem INTEGER NOT NULL DEFAULT 0;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXtimeDownloaded INTEGER NOT NULL DEFAULT 0;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=14
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=13;

# A_GalleryCheckoutTransaction_1.14
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagConfirmed;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagPaid;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagCleared;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagFulfil;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagFulfilled;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagCompleted;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagHold;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagProblem;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagDownloaded;

CALL ADMIN_CMD ('REORG TABLE DB_TABLE_PREFIXCheckoutTransaction');

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=15
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=14;

# A_GalleryCheckoutTransaction_1.2
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXpaymentPlugin VARCHAR(128);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagPaid SMALLINT;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagCleared SMALLINT;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=3
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=2;

# A_GalleryCheckoutTransaction_1.3
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagFulfil SMALLINT;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagFulfilled SMALLINT;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagCompleted SMALLINT;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagHold SMALLINT;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagProblem SMALLINT;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=4
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=3;

# A_GalleryCheckoutTransaction_1.4
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXflagDownloaded SMALLINT;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=5
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=4;

# A_GalleryCheckoutTransaction_1.5
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXdownloadAttempts INTEGER;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=6
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=5;

# A_GalleryCheckoutTransaction_1.6
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXcustComments VARCHAR(15000);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=7
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=6;

# A_GalleryCheckoutTransaction_1.7
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXpostageType VARCHAR(128);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=8
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=7;

# A_GalleryCheckoutTransaction_1.8
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXsecurity VARCHAR(32) NOT NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=9
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=8;

# A_GalleryCheckoutTransaction_1.9
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXdiscount VARCHAR(32);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXdiscountDescription VARCHAR(128);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=10
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=9;

# CheckoutDiscountMap
CREATE TABLE DB_TABLE_PREFIXCheckoutDiscountMap(
 DB_COLUMN_PREFIXdiscountId INTEGER NOT NULL,
 DB_COLUMN_PREFIXdescription VARCHAR(128),
 DB_COLUMN_PREFIXentryCode VARCHAR(32),
 DB_COLUMN_PREFIXminValue VARCHAR(32),
 DB_COLUMN_PREFIXminItems INTEGER,
 DB_COLUMN_PREFIXminProducts INTEGER,
 DB_COLUMN_PREFIXgroupId INTEGER,
 DB_COLUMN_PREFIXdiscountPercent VARCHAR(32),
 DB_COLUMN_PREFIXdiscountFixed VARCHAR(32),
 DB_COLUMN_PREFIXfreePostage SMALLINT,
 DB_COLUMN_PREFIXapplyDefault SMALLINT,
 DB_COLUMN_PREFIXpriority INTEGER
);

CREATE INDEX DB_TABLE_PREFIXCheck39_6217
   ON DB_TABLE_PREFIXCheckoutDiscountMap(DB_COLUMN_PREFIXdiscountId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutDiscountMap', 1, 1);

# CheckoutProductMap
CREATE TABLE DB_TABLE_PREFIXCheckoutProductMap(
 DB_COLUMN_PREFIXproductId INTEGER NOT NULL,
 DB_COLUMN_PREFIXparamName VARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXparamValue VARCHAR(10000) NOT NULL,
 DB_COLUMN_PREFIXownerId INTEGER NOT NULL
);

CREATE INDEX DB_TABLE_PREFIXCheck53_37925
   ON DB_TABLE_PREFIXCheckoutProductMap(DB_COLUMN_PREFIXproductId);

CREATE INDEX DB_TABLE_PREFIXCheck53_21573
   ON DB_TABLE_PREFIXCheckoutProductMap(DB_COLUMN_PREFIXownerId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutProductMap', 1, 0);

# GalleryCheckoutItem
CREATE TABLE DB_TABLE_PREFIXCheckoutItem(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXitem INTEGER NOT NULL,
 DB_COLUMN_PREFIXtransaction INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemName VARCHAR(128),
 DB_COLUMN_PREFIXitemText VARCHAR(128),
 DB_COLUMN_PREFIXproduct INTEGER NOT NULL,
 DB_COLUMN_PREFIXproductName VARCHAR(128),
 DB_COLUMN_PREFIXqty INTEGER NOT NULL,
 DB_COLUMN_PREFIXpriceEach VARCHAR(32),
 DB_COLUMN_PREFIXpriceTotal VARCHAR(32),
 DB_COLUMN_PREFIXnotes VARCHAR(15000)
);

ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

CREATE INDEX DB_TABLE_PREFIXCheck48_72670
   ON DB_TABLE_PREFIXCheckoutItem(DB_COLUMN_PREFIXitem);

CREATE INDEX DB_TABLE_PREFIXCheck48_8593
   ON DB_TABLE_PREFIXCheckoutItem(DB_COLUMN_PREFIXtransaction);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutItem', 1, 3);

# GalleryCheckoutTransaction
CREATE TABLE DB_TABLE_PREFIXCheckoutTransaction(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXdate INTEGER NOT NULL,
 DB_COLUMN_PREFIXsecurity VARCHAR(32) NOT NULL,
 DB_COLUMN_PREFIXbuyerId INTEGER NOT NULL,
 DB_COLUMN_PREFIXhost VARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXlanguageCode VARCHAR(32),
 DB_COLUMN_PREFIXpostage VARCHAR(32),
 DB_COLUMN_PREFIXpostageType VARCHAR(128),
 DB_COLUMN_PREFIXdiscount VARCHAR(32),
 DB_COLUMN_PREFIXdiscountDescription VARCHAR(128),
 DB_COLUMN_PREFIXamount VARCHAR(32),
 DB_COLUMN_PREFIXfirstName VARCHAR(128),
 DB_COLUMN_PREFIXlastName VARCHAR(128),
 DB_COLUMN_PREFIXemail VARCHAR(128),
 DB_COLUMN_PREFIXrecipientName VARCHAR(128),
 DB_COLUMN_PREFIXtelephone VARCHAR(128),
 DB_COLUMN_PREFIXaddress1 VARCHAR(128),
 DB_COLUMN_PREFIXaddress2 VARCHAR(128),
 DB_COLUMN_PREFIXaddress3 VARCHAR(128),
 DB_COLUMN_PREFIXaddress4 VARCHAR(128),
 DB_COLUMN_PREFIXaddress5 VARCHAR(128),
 DB_COLUMN_PREFIXaddressZip VARCHAR(128),
 DB_COLUMN_PREFIXaddressCountry VARCHAR(128),
 DB_COLUMN_PREFIXcustNotes VARCHAR(15000),
 DB_COLUMN_PREFIXcustComments VARCHAR(15000),
 DB_COLUMN_PREFIXpaymentPlugin VARCHAR(128),
 DB_COLUMN_PREFIXtimeConfirmed INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimePaid INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeCleared INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeFulfil INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeFulfilled INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeCompleted INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeHold INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeProblem INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeDownloaded INTEGER NOT NULL,
 DB_COLUMN_PREFIXdownloadAttempts INTEGER NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

CREATE INDEX DB_TABLE_PREFIXCheck1f_95610
   ON DB_TABLE_PREFIXCheckoutTransaction(DB_COLUMN_PREFIXdate);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutTransaction', 1, 15);

## mssql
# A_CheckoutDiscountMap_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutDiscountMap ADD DB_COLUMN_PREFIXgroupId INT NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutDiscountMap' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutDiscountMap_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutDiscountMap ADD DB_COLUMN_PREFIXgroupId INT NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutDiscountMap' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutItem_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD DB_COLUMN_PREFIXqtyTemp INT;

UPDATE DB_TABLE_PREFIXCheckoutItem SET DB_COLUMN_PREFIXqtyTemp = CAST(DB_COLUMN_PREFIXqty AS INT);

ALTER TABLE DB_TABLE_PREFIXCheckoutItem DROP COLUMN DB_COLUMN_PREFIXqty;

ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD DB_COLUMN_PREFIXqty INT;

UPDATE DB_TABLE_PREFIXCheckoutItem SET DB_COLUMN_PREFIXqty = DB_COLUMN_PREFIXqtyTemp;

ALTER TABLE DB_TABLE_PREFIXCheckoutItem DROP COLUMN DB_COLUMN_PREFIXqtyTemp;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutItem_1.1
ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD DB_COLUMN_PREFIXtransaction INT NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=2
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=1;

# A_GalleryCheckoutItem_1.2
ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD DB_COLUMN_PREFIXitemText NVARCHAR(128) NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=3
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=2;

# A_GalleryCheckoutTransaction_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppId;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppStatus;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppDate;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppSign;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppFirstName;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppLastName;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppEmail;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXnotes;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXfirstName NVARCHAR(128) NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXlastName NVARCHAR(128) NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXemail NVARCHAR(128) NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXrecipientName NVARCHAR(128) NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXaddress1 NVARCHAR(128) NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXaddress2 NVARCHAR(128) NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXaddress3 NVARCHAR(128) NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXaddress4 NVARCHAR(128) NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXaddress5 NVARCHAR(128) NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXaddressZip NVARCHAR(128) NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXaddressCountry NVARCHAR(128) NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXcustNotes NVARCHAR(MAX) NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutTransaction_1.1
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXamountTemp NVARCHAR(32);

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXamountTemp = CAST(DB_COLUMN_PREFIXamount AS NVARCHAR(32));

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXamount;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXamount NVARCHAR(32);

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXamount = DB_COLUMN_PREFIXamountTemp;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXamountTemp;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXpostage NVARCHAR(32) NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=2
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=1;

# A_GalleryCheckoutTransaction_1.10
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXlanguageCode NVARCHAR(32) NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=11
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=10;

# A_GalleryCheckoutTransaction_1.11
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtelephone NVARCHAR(128) NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=12
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=11;

# A_GalleryCheckoutTransaction_1.12
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagConfirmed BIT NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=13
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=12;

# A_GalleryCheckoutTransaction_1.13
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeConfirmed INT DEFAULT '0' NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimePaid INT DEFAULT '0' NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeCleared INT DEFAULT '0' NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeFulfil INT DEFAULT '0' NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeFulfilled INT DEFAULT '0' NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeCompleted INT DEFAULT '0' NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeHold INT DEFAULT '0' NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeProblem INT DEFAULT '0' NOT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeDownloaded INT DEFAULT '0' NOT NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=14
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=13;

# A_GalleryCheckoutTransaction_1.14
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagConfirmed;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagPaid;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagCleared;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagFulfil;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagFulfilled;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagCompleted;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagHold;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagProblem;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagDownloaded;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=15
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=14;

# A_GalleryCheckoutTransaction_1.2
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXpaymentPlugin NVARCHAR(128) NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagPaid BIT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagCleared BIT NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=3
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=2;

# A_GalleryCheckoutTransaction_1.3
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagFulfil BIT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagFulfilled BIT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagCompleted BIT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagHold BIT NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagProblem BIT NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=4
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=3;

# A_GalleryCheckoutTransaction_1.4
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagDownloaded BIT NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=5
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=4;

# A_GalleryCheckoutTransaction_1.5
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXdownloadAttempts INT NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=6
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=5;

# A_GalleryCheckoutTransaction_1.6
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXcustComments NVARCHAR(MAX) NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=7
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=6;

# A_GalleryCheckoutTransaction_1.7
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXpostageType NVARCHAR(128) NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=8
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=7;

# A_GalleryCheckoutTransaction_1.8
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXsecurity NVARCHAR(32) NOT NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=9
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=8;

# A_GalleryCheckoutTransaction_1.9
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXdiscount NVARCHAR(32) NULL;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXdiscountDescription NVARCHAR(128) NULL;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=10
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=9;

# CheckoutDiscountMap
CREATE TABLE DB_TABLE_PREFIXCheckoutDiscountMap(
 DB_COLUMN_PREFIXdiscountId INT NOT NULL,
 DB_COLUMN_PREFIXdescription NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXentryCode NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXminValue NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXminItems INT NULL,
 DB_COLUMN_PREFIXminProducts INT NULL,
 DB_COLUMN_PREFIXgroupId INT NULL,
 DB_COLUMN_PREFIXdiscountPercent NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXdiscountFixed NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXfreePostage BIT NULL,
 DB_COLUMN_PREFIXapplyDefault BIT NULL,
 DB_COLUMN_PREFIXpriority INT NULL
);

CREATE INDEX DB_TABLE_PREFIXCheckoutDiscountMap_6217 ON DB_TABLE_PREFIXCheckoutDiscountMap(DB_COLUMN_PREFIXdiscountId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutDiscountMap', 1, 1);

# CheckoutProductMap
CREATE TABLE DB_TABLE_PREFIXCheckoutProductMap(
 DB_COLUMN_PREFIXproductId INT NOT NULL,
 DB_COLUMN_PREFIXparamName NVARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXparamValue NVARCHAR(MAX) NOT NULL,
 DB_COLUMN_PREFIXownerId INT NOT NULL
);

CREATE INDEX DB_TABLE_PREFIXCheckoutProductMap_37925 ON DB_TABLE_PREFIXCheckoutProductMap(DB_COLUMN_PREFIXproductId);

CREATE INDEX DB_TABLE_PREFIXCheckoutProductMap_21573 ON DB_TABLE_PREFIXCheckoutProductMap(DB_COLUMN_PREFIXownerId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutProductMap', 1, 0);

# GalleryCheckoutItem
CREATE TABLE DB_TABLE_PREFIXCheckoutItem(
 DB_COLUMN_PREFIXid INT NOT NULL,
 DB_COLUMN_PREFIXitem INT NOT NULL,
 DB_COLUMN_PREFIXtransaction INT NOT NULL,
 DB_COLUMN_PREFIXitemName NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXitemText NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXproduct INT NOT NULL,
 DB_COLUMN_PREFIXproductName NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXqty INT NOT NULL,
 DB_COLUMN_PREFIXpriceEach NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXpriceTotal NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXnotes NVARCHAR(MAX) NULL
);

ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

CREATE INDEX DB_TABLE_PREFIXCheckoutItem_72670 ON DB_TABLE_PREFIXCheckoutItem(DB_COLUMN_PREFIXitem);

CREATE INDEX DB_TABLE_PREFIXCheckoutItem_8593 ON DB_TABLE_PREFIXCheckoutItem(DB_COLUMN_PREFIXtransaction);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutItem', 1, 3);

# GalleryCheckoutTransaction
CREATE TABLE DB_TABLE_PREFIXCheckoutTransaction(
 DB_COLUMN_PREFIXid INT NOT NULL,
 DB_COLUMN_PREFIXdate INT NOT NULL,
 DB_COLUMN_PREFIXsecurity NVARCHAR(32) NOT NULL,
 DB_COLUMN_PREFIXbuyerId INT NOT NULL,
 DB_COLUMN_PREFIXhost NVARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXlanguageCode NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXpostage NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXpostageType NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXdiscount NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXdiscountDescription NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXamount NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXfirstName NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXlastName NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXemail NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXrecipientName NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXtelephone NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXaddress1 NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXaddress2 NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXaddress3 NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXaddress4 NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXaddress5 NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXaddressZip NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXaddressCountry NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXcustNotes NVARCHAR(MAX) NULL,
 DB_COLUMN_PREFIXcustComments NVARCHAR(MAX) NULL,
 DB_COLUMN_PREFIXpaymentPlugin NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXtimeConfirmed INT NOT NULL,
 DB_COLUMN_PREFIXtimePaid INT NOT NULL,
 DB_COLUMN_PREFIXtimeCleared INT NOT NULL,
 DB_COLUMN_PREFIXtimeFulfil INT NOT NULL,
 DB_COLUMN_PREFIXtimeFulfilled INT NOT NULL,
 DB_COLUMN_PREFIXtimeCompleted INT NOT NULL,
 DB_COLUMN_PREFIXtimeHold INT NOT NULL,
 DB_COLUMN_PREFIXtimeProblem INT NOT NULL,
 DB_COLUMN_PREFIXtimeDownloaded INT NOT NULL,
 DB_COLUMN_PREFIXdownloadAttempts INT NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

CREATE INDEX DB_TABLE_PREFIXCheckoutTransaction_95610 ON DB_TABLE_PREFIXCheckoutTransaction(DB_COLUMN_PREFIXdate);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutTransaction', 1, 15);

## sqlite
# A_CheckoutDiscountMap_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutDiscountMap ADD DB_COLUMN_PREFIXgroupId INTEGER;
VACUUM DB_TABLE_PREFIXCheckoutDiscountMap;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutDiscountMap' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutDiscountMap_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutDiscountMap ADD DB_COLUMN_PREFIXgroupId INTEGER;
VACUUM DB_TABLE_PREFIXCheckoutDiscountMap;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutDiscountMap' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutItem_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD COLUMN DB_COLUMN_PREFIXqtyTemp INTEGER;

VACUUM DB_TABLE_PREFIXCheckoutItem;

UPDATE DB_TABLE_PREFIXCheckoutItem SET DB_COLUMN_PREFIXqtyTemp = DB_COLUMN_PREFIXqty;

ALTER TABLE DB_TABLE_PREFIXCheckoutItem DROP COLUMN DB_COLUMN_PREFIXqty;

ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD COLUMN DB_COLUMN_PREFIXqty INTEGER;

VACUUM DB_TABLE_PREFIXCheckoutItem;

UPDATE DB_TABLE_PREFIXCheckoutItem SET DB_COLUMN_PREFIXqty = DB_COLUMN_PREFIXqtyTemp;

ALTER TABLE DB_TABLE_PREFIXCheckoutItem DROP COLUMN DB_COLUMN_PREFIXqtyTemp;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutItem_1.1
ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD DB_COLUMN_PREFIXtransaction INTEGER;
VACUUM DB_TABLE_PREFIXCheckoutItem;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=2
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=1;

# A_GalleryCheckoutItem_1.2
ALTER TABLE DB_TABLE_PREFIXCheckoutItem ADD DB_COLUMN_PREFIXitemText TEXT;
VACUUM DB_TABLE_PREFIXCheckoutItem;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=3
  WHERE DB_COLUMN_PREFIXname='CheckoutItem' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=2;

# A_GalleryCheckoutTransaction_1.0
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppId;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppStatus;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppDate;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppSign;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppFirstName;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppLastName;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXppEmail;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXnotes;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXfirstName TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXlastName TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXemail TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXrecipientName TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXaddress1 TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXaddress2 TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXaddress3 TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXaddress4 TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXaddress5 TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXaddressZip TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXaddressCountry TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXcustNotes TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

# A_GalleryCheckoutTransaction_1.1
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXamountTemp TEXT;

VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXamountTemp = DB_COLUMN_PREFIXamount;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXamount;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD COLUMN DB_COLUMN_PREFIXamount TEXT;

VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXCheckoutTransaction SET DB_COLUMN_PREFIXamount = DB_COLUMN_PREFIXamountTemp;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXamountTemp;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXpostage TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=2
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=1;

# A_GalleryCheckoutTransaction_1.10
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXlanguageCode TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=11
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=10;

# A_GalleryCheckoutTransaction_1.11
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtelephone TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=12
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=11;

# A_GalleryCheckoutTransaction_1.12
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagConfirmed INTEGER;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=13
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=12;

# A_GalleryCheckoutTransaction_1.13
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeConfirmed INTEGER NOT NULL DEFAULT '0';
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimePaid INTEGER NOT NULL DEFAULT '0';
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeCleared INTEGER NOT NULL DEFAULT '0';
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeFulfil INTEGER NOT NULL DEFAULT '0';
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeFulfilled INTEGER NOT NULL DEFAULT '0';
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeCompleted INTEGER NOT NULL DEFAULT '0';
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeHold INTEGER NOT NULL DEFAULT '0';
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeProblem INTEGER NOT NULL DEFAULT '0';
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXtimeDownloaded INTEGER NOT NULL DEFAULT '0';
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=14
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=13;

# A_GalleryCheckoutTransaction_1.14
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagConfirmed;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagPaid;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagCleared;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagFulfil;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagFulfilled;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagCompleted;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagHold;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagProblem;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction DROP COLUMN DB_COLUMN_PREFIXflagDownloaded;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=15
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=14;

# A_GalleryCheckoutTransaction_1.2
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXpaymentPlugin TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagPaid INTEGER;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagCleared INTEGER;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=3
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=2;

# A_GalleryCheckoutTransaction_1.3
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagFulfil INTEGER;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagFulfilled INTEGER;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagCompleted INTEGER;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagHold INTEGER;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagProblem INTEGER;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=4
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=3;

# A_GalleryCheckoutTransaction_1.4
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXflagDownloaded INTEGER;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=5
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=4;

# A_GalleryCheckoutTransaction_1.5
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXdownloadAttempts INTEGER;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=6
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=5;

# A_GalleryCheckoutTransaction_1.6
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXcustComments TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=7
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=6;

# A_GalleryCheckoutTransaction_1.7
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXpostageType TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=8
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=7;

# A_GalleryCheckoutTransaction_1.8
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXsecurity TEXT NOT NULL;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=9
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=8;

# A_GalleryCheckoutTransaction_1.9
ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXdiscount TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

ALTER TABLE DB_TABLE_PREFIXCheckoutTransaction ADD DB_COLUMN_PREFIXdiscountDescription TEXT;
VACUUM DB_TABLE_PREFIXCheckoutTransaction;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=10
  WHERE DB_COLUMN_PREFIXname='CheckoutTransaction' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=9;

# CheckoutDiscountMap
CREATE TABLE DB_TABLE_PREFIXCheckoutDiscountMap(
 DB_COLUMN_PREFIXdiscountId INTEGER NOT NULL,
 DB_COLUMN_PREFIXdescription TEXT,
 DB_COLUMN_PREFIXentryCode TEXT,
 DB_COLUMN_PREFIXminValue TEXT,
 DB_COLUMN_PREFIXminItems INTEGER,
 DB_COLUMN_PREFIXminProducts INTEGER,
 DB_COLUMN_PREFIXgroupId INTEGER,
 DB_COLUMN_PREFIXdiscountPercent TEXT,
 DB_COLUMN_PREFIXdiscountFixed TEXT,
 DB_COLUMN_PREFIXfreePostage INTEGER,
 DB_COLUMN_PREFIXapplyDefault INTEGER,
 DB_COLUMN_PREFIXpriority INTEGER
);

CREATE INDEX DB_TABLE_PREFIXCheckoutDiscountMap_6217 ON DB_TABLE_PREFIXCheckoutDiscountMap(DB_COLUMN_PREFIXdiscountId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutDiscountMap', 1, 1);

# CheckoutProductMap
CREATE TABLE DB_TABLE_PREFIXCheckoutProductMap(
 DB_COLUMN_PREFIXproductId INTEGER NOT NULL,
 DB_COLUMN_PREFIXparamName TEXT NOT NULL,
 DB_COLUMN_PREFIXparamValue TEXT NOT NULL,
 DB_COLUMN_PREFIXownerId INTEGER NOT NULL
);

CREATE INDEX DB_TABLE_PREFIXCheckoutProductMap_37925 ON DB_TABLE_PREFIXCheckoutProductMap(DB_COLUMN_PREFIXproductId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutProductMap', 1, 0);

# GalleryCheckoutItem
CREATE TABLE DB_TABLE_PREFIXCheckoutItem(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXitem INTEGER NOT NULL,
 DB_COLUMN_PREFIXtransaction INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemName TEXT,
 DB_COLUMN_PREFIXitemText TEXT,
 DB_COLUMN_PREFIXproduct INTEGER NOT NULL,
 DB_COLUMN_PREFIXproductName TEXT,
 DB_COLUMN_PREFIXqty INTEGER NOT NULL,
 DB_COLUMN_PREFIXpriceEach TEXT,
 DB_COLUMN_PREFIXpriceTotal TEXT,
 DB_COLUMN_PREFIXnotes TEXT
);

CREATE UNIQUE INDEX DB_TABLE_PREFIXCheckoutItem_pkey ON DB_TABLE_PREFIXCheckoutItem(DB_COLUMN_PREFIXid);

CREATE INDEX DB_TABLE_PREFIXCheckoutItem_72670 ON DB_TABLE_PREFIXCheckoutItem(DB_COLUMN_PREFIXitem);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutItem', 1, 3);

# GalleryCheckoutTransaction
CREATE TABLE DB_TABLE_PREFIXCheckoutTransaction(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXdate INTEGER NOT NULL,
 DB_COLUMN_PREFIXsecurity TEXT NOT NULL,
 DB_COLUMN_PREFIXbuyerId INTEGER NOT NULL,
 DB_COLUMN_PREFIXhost TEXT NOT NULL,
 DB_COLUMN_PREFIXlanguageCode TEXT,
 DB_COLUMN_PREFIXpostage TEXT,
 DB_COLUMN_PREFIXpostageType TEXT,
 DB_COLUMN_PREFIXdiscount TEXT,
 DB_COLUMN_PREFIXdiscountDescription TEXT,
 DB_COLUMN_PREFIXamount TEXT,
 DB_COLUMN_PREFIXfirstName TEXT,
 DB_COLUMN_PREFIXlastName TEXT,
 DB_COLUMN_PREFIXemail TEXT,
 DB_COLUMN_PREFIXrecipientName TEXT,
 DB_COLUMN_PREFIXtelephone TEXT,
 DB_COLUMN_PREFIXaddress1 TEXT,
 DB_COLUMN_PREFIXaddress2 TEXT,
 DB_COLUMN_PREFIXaddress3 TEXT,
 DB_COLUMN_PREFIXaddress4 TEXT,
 DB_COLUMN_PREFIXaddress5 TEXT,
 DB_COLUMN_PREFIXaddressZip TEXT,
 DB_COLUMN_PREFIXaddressCountry TEXT,
 DB_COLUMN_PREFIXcustNotes TEXT,
 DB_COLUMN_PREFIXcustComments TEXT,
 DB_COLUMN_PREFIXpaymentPlugin TEXT,
 DB_COLUMN_PREFIXtimeConfirmed INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimePaid INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeCleared INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeFulfil INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeFulfilled INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeCompleted INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeHold INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeProblem INTEGER NOT NULL,
 DB_COLUMN_PREFIXtimeDownloaded INTEGER NOT NULL,
 DB_COLUMN_PREFIXdownloadAttempts INTEGER NOT NULL
);

CREATE UNIQUE INDEX DB_TABLE_PREFIXCheckoutTransaction_pkey ON DB_TABLE_PREFIXCheckoutTransaction(DB_COLUMN_PREFIXid);

CREATE INDEX DB_TABLE_PREFIXCheckoutTransaction_95610 ON DB_TABLE_PREFIXCheckoutTransaction(DB_COLUMN_PREFIXdate);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutTransaction', 1, 15);

