## mysql
# GalleryCheckoutPaypalIPN
CREATE TABLE DB_TABLE_PREFIXCheckoutPaypalIPN(
 DB_COLUMN_PREFIXid int(11) NOT NULL,
 DB_COLUMN_PREFIXppId varchar(128),
 DB_COLUMN_PREFIXppStatus varchar(128),
 DB_COLUMN_PREFIXppDate varchar(128),
 DB_COLUMN_PREFIXppSign varchar(128),
 DB_COLUMN_PREFIXnotes text,
 PRIMARY KEY(DB_COLUMN_PREFIXid)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutPaypalIPN', 1, 0);

## postgres
# GalleryCheckoutPaypalIPN
CREATE TABLE DB_TABLE_PREFIXCheckoutPaypalIPN(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXppId VARCHAR(128),
 DB_COLUMN_PREFIXppStatus VARCHAR(128),
 DB_COLUMN_PREFIXppDate VARCHAR(128),
 DB_COLUMN_PREFIXppSign VARCHAR(128),
 DB_COLUMN_PREFIXnotes text
);

ALTER TABLE DB_TABLE_PREFIXCheckoutPaypalIPN ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutPaypalIPN', 1, 0);

## oracle
# GalleryCheckoutPaypalIPN
CREATE TABLE DB_TABLE_PREFIXCheckoutPaypalIPN(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXppId VARCHAR2(128),
 DB_COLUMN_PREFIXppStatus VARCHAR2(128),
 DB_COLUMN_PREFIXppDate VARCHAR2(128),
 DB_COLUMN_PREFIXppSign VARCHAR2(128),
 DB_COLUMN_PREFIXnotes CLOB
);

ALTER TABLE DB_TABLE_PREFIXCheckoutPaypalIPN
 ADD PRIMARY KEY (DB_COLUMN_PREFIXid)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutPaypalIPN', 1, 0);

## db2
# GalleryCheckoutPaypalIPN
CREATE TABLE DB_TABLE_PREFIXCheckoutPaypalIPN(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXppId VARCHAR(128),
 DB_COLUMN_PREFIXppStatus VARCHAR(128),
 DB_COLUMN_PREFIXppDate VARCHAR(128),
 DB_COLUMN_PREFIXppSign VARCHAR(128),
 DB_COLUMN_PREFIXnotes VARCHAR(15000)
);

ALTER TABLE DB_TABLE_PREFIXCheckoutPaypalIPN ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutPaypalIPN', 1, 0);

## mssql
# GalleryCheckoutPaypalIPN
CREATE TABLE DB_TABLE_PREFIXCheckoutPaypalIPN(
 DB_COLUMN_PREFIXid INT NOT NULL,
 DB_COLUMN_PREFIXppId NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXppStatus NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXppDate NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXppSign NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXnotes NVARCHAR(MAX) NULL
);

ALTER TABLE DB_TABLE_PREFIXCheckoutPaypalIPN ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutPaypalIPN', 1, 0);

