<?php

// $Id: frame.inc 908 2007-03-01 01:29:39Z andy_st $
$frameData = array(
	'name'      => $gallery->i18n('X_Brown_Croped - 14px (gif)'),

	// Top Left
	'imageTL'   => 'TL.gif',
	'widthTL'   => 28,
	'heightTL'  => 28,

	// Top
	'imageTTL'  => '',
	'widthTTL'  => 0,
	'imageTT'   => 'TT.gif',
	'heightTT'  => 28,
	'imageTTR'  => '',
	'widthTTR'  => 0,

	// Top Right
	'imageTR'   => 'TR.gif',
	'widthTR'   => 28,
	'heightTR'  => 28,

	// Left
	'imageLLT'  => '',
	'heightLLT' => 0,
	'imageLL'   => 'LL.gif',
	'widthLL'   => 28,
	'imageLLB'  => '',
	'heightLLB' => 0,

	// Right
	'imageRRT'  => '',
	'heightRRT' => 0,
	'imageRR'   => 'RR.gif',
	'widthRR'   => 28,
	'imageRRB'  => '',
	'heightRRB' => 0,

	// Bottom Left
	'imageBL'   => 'BL.gif',
	'widthBL'   => 28,
	'heightBL'  => 28,

	// Bottom
	'imageBBL'  => '',
	'widthBBL'  => 0,
	'imageBB'   => 'BB.gif',
	'heightBB'  => 28,
	'imageBBR'  => '',
	'widthBBR'  => 0,

	// Bottom Right
	'imageBR'   => 'BR.gif',
	'widthBR'   => 28,
	'heightBR'  => 28,
);
