<?php
// $Id: frame.inc,v 1.1 2004/07/21 01:26:20 mindless Exp $
$frameData = array(
	'name'      => $gallery->i18n('PG_WS_15px'),

	// Top Left
	'imageTL'   => 'TL.gif',
	'widthTL'   => 26,
	'heightTL'  => 26,

	// Top
	'imageTTL'  => '',
	'widthTTL'  => 0,

	'imageTT'   => 'TT.gif',
	'heightTT'  => 26,

	'imageTTR'  => '',
	'widthTTR'  => 0,

	// Top Right
	'imageTR'   => 'TR.gif',
	'widthTR'   => 26,
	'heightTR'  => 26,

	// Left
	'imageLLT'  => '',
	'heightLLT' => 0,

	'imageLL'   => 'LL.gif',
	'widthLL'   => 26,

	'imageLLB'  => '',
	'heightLLB' => 0,

	// Right
	'imageRRT'  => '',
	'heightRRT' => 0,

	'imageRR'   => 'RR.gif',
	'widthRR'   => 26,

	'imageRRB'  => '',
	'heightRRB' => 0,

	// Bottom Left
	'imageBL'   => 'BL.gif',
	'widthBL'   => 26,
	'heightBL'  => 26,

	// Bottom
	'imageBBL'  => '',
	'widthBBL'  => 0,

	'imageBB'   => 'BB.gif',
	'heightBB'  => 26,

	'imageBBR'  => '',
	'widthBBR'  => 0,

	// Bottom Right
	'imageBR'   => 'BR.gif',
	'widthBR'   => 26,
	'heightBR'  => 26,

);
