## mysql
# SimpleviewerParameterMap
CREATE TABLE DB_TABLE_PREFIXSimpleviewerParameterMap(
 DB_COLUMN_PREFIXid int(11) NOT NULL,
 DB_COLUMN_PREFIXparamName varchar(128),
 DB_COLUMN_PREFIXparamValue text,
 DB_COLUMN_PREFIXalbumId int(11) NOT NULL,
 DB_COLUMN_PREFIXcategory varchar(32),
 INDEX DB_TABLE_PREFIXSimpleviewerParameterMap_10256(DB_COLUMN_PREFIXid),
 INDEX DB_TABLE_PREFIXSimpleviewerParameterMap_14323(DB_COLUMN_PREFIXalbumId),
 INDEX DB_TABLE_PREFIXSimpleviewerParameterMap_50625(DB_COLUMN_PREFIXcategory)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('SimpleviewerParameterMap', 1, 0);

## postgres
# SimpleviewerParameterMap
CREATE TABLE DB_TABLE_PREFIXSimpleviewerParameterMap(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXparamName VARCHAR(128),
 DB_COLUMN_PREFIXparamValue text,
 DB_COLUMN_PREFIXalbumId INTEGER NOT NULL,
 DB_COLUMN_PREFIXcategory VARCHAR(32)
);

CREATE INDEX DB_TABLE_PREFIXSimpleviewerParameterMap_10256 ON DB_TABLE_PREFIXSimpleviewerParameterMap(DB_COLUMN_PREFIXid);

CREATE INDEX DB_TABLE_PREFIXSimpleviewerParameterMap_14323 ON DB_TABLE_PREFIXSimpleviewerParameterMap(DB_COLUMN_PREFIXalbumId);

CREATE INDEX DB_TABLE_PREFIXSimpleviewerParameterMap_50625 ON DB_TABLE_PREFIXSimpleviewerParameterMap(DB_COLUMN_PREFIXcategory);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('SimpleviewerParameterMap', 1, 0);

## oracle
# SimpleviewerParameterMap
CREATE TABLE DB_TABLE_PREFIXSimpleviewerParameterMap(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXparamName VARCHAR2(128),
 DB_COLUMN_PREFIXparamValue VARCHAR2(4000),
 DB_COLUMN_PREFIXalbumId INTEGER NOT NULL,
 DB_COLUMN_PREFIXcategory VARCHAR2(32)
);

CREATE INDEX DB_TABLE_PREFIXSimpleviewerParameterMap_10256
   ON DB_TABLE_PREFIXSimpleviewerParameterMap(DB_COLUMN_PREFIXid);

CREATE INDEX DB_TABLE_PREFIXSimpleviewerParameterMap_14323
   ON DB_TABLE_PREFIXSimpleviewerParameterMap(DB_COLUMN_PREFIXalbumId);

CREATE INDEX DB_TABLE_PREFIXSimpleviewerParameterMap_50625
   ON DB_TABLE_PREFIXSimpleviewerParameterMap(DB_COLUMN_PREFIXcategory);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('SimpleviewerParameterMap', 1, 0);

## db2
# SimpleviewerParameterMap
CREATE TABLE DB_TABLE_PREFIXSimpleviewerParameterMap(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXparamName VARCHAR(128),
 DB_COLUMN_PREFIXparamValue VARCHAR(10000),
 DB_COLUMN_PREFIXalbumId INTEGER NOT NULL,
 DB_COLUMN_PREFIXcategory VARCHAR(32)
);

CREATE INDEX DB_TABLE_PREFIXSimpl40_10256
   ON DB_TABLE_PREFIXSimpleviewerParameterMap(DB_COLUMN_PREFIXid);

CREATE INDEX DB_TABLE_PREFIXSimpl40_14323
   ON DB_TABLE_PREFIXSimpleviewerParameterMap(DB_COLUMN_PREFIXalbumId);

CREATE INDEX DB_TABLE_PREFIXSimpl40_50625
   ON DB_TABLE_PREFIXSimpleviewerParameterMap(DB_COLUMN_PREFIXcategory);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('SimpleviewerParameterMap', 1, 0);

## mssql
# SimpleviewerParameterMap
CREATE TABLE DB_TABLE_PREFIXSimpleviewerParameterMap(
 DB_COLUMN_PREFIXid INT NOT NULL,
 DB_COLUMN_PREFIXparamName NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXparamValue NVARCHAR(MAX) NULL,
 DB_COLUMN_PREFIXalbumId INT NOT NULL,
 DB_COLUMN_PREFIXcategory NVARCHAR(32) NULL
);

CREATE INDEX DB_TABLE_PREFIXSimpleviewerParameterMap_10256 ON DB_TABLE_PREFIXSimpleviewerParameterMap(DB_COLUMN_PREFIXid);

CREATE INDEX DB_TABLE_PREFIXSimpleviewerParameterMap_14323 ON DB_TABLE_PREFIXSimpleviewerParameterMap(DB_COLUMN_PREFIXalbumId);

CREATE INDEX DB_TABLE_PREFIXSimpleviewerParameterMap_50625 ON DB_TABLE_PREFIXSimpleviewerParameterMap(DB_COLUMN_PREFIXcategory);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('SimpleviewerParameterMap', 1, 0);

