## mysql
# ICalendarResourceItem
CREATE TABLE DB_TABLE_PREFIXICalendarResourceItem(
 DB_COLUMN_PREFIXid int(11) NOT NULL,
 PRIMARY KEY(DB_COLUMN_PREFIXid)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ICalendarResourceItem', 0, 1);

# ICalendarResourceMap
CREATE TABLE DB_TABLE_PREFIXICalendarResourceMap(
 DB_COLUMN_PREFIXresourceId int(11),
 DB_COLUMN_PREFIXresourceSerialNumber int(11),
 DB_COLUMN_PREFIXentityId int(11),
 DB_COLUMN_PREFIXentitySerialNumber int(11),
 DB_COLUMN_PREFIXstartOffset int(11),
 DB_COLUMN_PREFIXendOffset int(11)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ICalendarResourceMap', 0, 1);

## postgres
# ICalendarResourceItem
CREATE TABLE DB_TABLE_PREFIXICalendarResourceItem(
 DB_COLUMN_PREFIXid INTEGER NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXICalendarResourceItem ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ICalendarResourceItem', 0, 1);

# ICalendarResourceMap
CREATE TABLE DB_TABLE_PREFIXICalendarResourceMap(
 DB_COLUMN_PREFIXresourceId INTEGER,
 DB_COLUMN_PREFIXresourceSerialNumber INTEGER,
 DB_COLUMN_PREFIXentityId INTEGER,
 DB_COLUMN_PREFIXentitySerialNumber INTEGER,
 DB_COLUMN_PREFIXstartOffset INTEGER,
 DB_COLUMN_PREFIXendOffset INTEGER);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ICalendarResourceMap', 0, 1);

## oracle
# ICalendarResourceItem
CREATE TABLE DB_TABLE_PREFIXICalendarResourceItem(
 DB_COLUMN_PREFIXid INTEGER NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXICalendarResourceItem
 ADD PRIMARY KEY (DB_COLUMN_PREFIXid)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ICalendarResourceItem', 0, 1);

# ICalendarResourceMap
CREATE TABLE DB_TABLE_PREFIXICalendarResourceMap(
 DB_COLUMN_PREFIXresourceId INTEGER,
 DB_COLUMN_PREFIXresourceSerialNumber INTEGER,
 DB_COLUMN_PREFIXentityId INTEGER,
 DB_COLUMN_PREFIXentitySerialNumber INTEGER,
 DB_COLUMN_PREFIXstartOffset INTEGER,
 DB_COLUMN_PREFIXendOffset INTEGER);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ICalendarResourceMap', 0, 1);

## db2
# ICalendarResourceItem
CREATE TABLE DB_TABLE_PREFIXICalendarResourceItem(
 DB_COLUMN_PREFIXid INTEGER NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXICalendarResourceItem ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ICalendarResourceItem', 0, 1);

# ICalendarResourceMap
CREATE TABLE DB_TABLE_PREFIXICalendarResourceMap(
 DB_COLUMN_PREFIXresourceId INTEGER,
 DB_COLUMN_PREFIXresourceSerialNumber INTEGER,
 DB_COLUMN_PREFIXentityId INTEGER,
 DB_COLUMN_PREFIXentitySerialNumber INTEGER,
 DB_COLUMN_PREFIXstartOffset INTEGER,
 DB_COLUMN_PREFIXendOffset INTEGER);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ICalendarResourceMap', 0, 1);

## mssql
# ICalendarResourceItem
CREATE TABLE DB_TABLE_PREFIXICalendarResourceItem(
 DB_COLUMN_PREFIXid INT NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXICalendarResourceItem ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ICalendarResourceItem', 0, 1);

# ICalendarResourceMap
CREATE TABLE DB_TABLE_PREFIXICalendarResourceMap(
 DB_COLUMN_PREFIXresourceId INT NULL,
 DB_COLUMN_PREFIXresourceSerialNumber INT NULL,
 DB_COLUMN_PREFIXentityId INT NULL,
 DB_COLUMN_PREFIXentitySerialNumber INT NULL,
 DB_COLUMN_PREFIXstartOffset INT NULL,
 DB_COLUMN_PREFIXendOffset INT NULL);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ICalendarResourceMap', 0, 1);

