## mysql
# FavouritesMap
CREATE TABLE DB_TABLE_PREFIXFavouritesMap(
 DB_COLUMN_PREFIXuserId int(11) NOT NULL,
 DB_COLUMN_PREFIXitemId int(11) NOT NULL,
 PRIMARY KEY(DB_COLUMN_PREFIXuserId, DB_COLUMN_PREFIXitemId),
 INDEX DB_TABLE_PREFIXFavouritesMap_75985(DB_COLUMN_PREFIXitemId)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('FavouritesMap', 1, 0);

## postgres
# FavouritesMap
CREATE TABLE DB_TABLE_PREFIXFavouritesMap(
 DB_COLUMN_PREFIXuserId INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXFavouritesMap ADD PRIMARY KEY (DB_COLUMN_PREFIXuserId, DB_COLUMN_PREFIXitemId);

CREATE INDEX DB_TABLE_PREFIXFavouritesMap_75985 ON DB_TABLE_PREFIXFavouritesMap(DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('FavouritesMap', 1, 0);

## oracle
# FavouritesMap
CREATE TABLE DB_TABLE_PREFIXFavouritesMap(
 DB_COLUMN_PREFIXuserId INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL
);

CREATE INDEX DB_TABLE_PREFIXFavouritesMap_75985
   ON DB_TABLE_PREFIXFavouritesMap(DB_COLUMN_PREFIXitemId);

ALTER TABLE DB_TABLE_PREFIXFavouritesMap
 ADD PRIMARY KEY (DB_COLUMN_PREFIXuserId, DB_COLUMN_PREFIXitemId)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('FavouritesMap', 1, 0);

## db2
# FavouritesMap
CREATE TABLE DB_TABLE_PREFIXFavouritesMap(
 DB_COLUMN_PREFIXuserId INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXFavouritesMap ADD PRIMARY KEY (DB_COLUMN_PREFIXuserId, DB_COLUMN_PREFIXitemId);

CREATE INDEX DB_TABLE_PREFIXFavou0e_75985
   ON DB_TABLE_PREFIXFavouritesMap(DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('FavouritesMap', 1, 0);

## mssql
# FavouritesMap
CREATE TABLE DB_TABLE_PREFIXFavouritesMap(
 DB_COLUMN_PREFIXuserId INT NOT NULL,
 DB_COLUMN_PREFIXitemId INT NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXFavouritesMap ADD PRIMARY KEY (DB_COLUMN_PREFIXuserId, DB_COLUMN_PREFIXitemId);

CREATE INDEX DB_TABLE_PREFIXFavouritesMap_75985 ON DB_TABLE_PREFIXFavouritesMap(DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('FavouritesMap', 1, 0);

