## mysql
# OpenIdMap
CREATE TABLE DB_TABLE_PREFIXOpenIdMap(
 DB_COLUMN_PREFIXopenId varchar(128),
 DB_COLUMN_PREFIXgalleryId int(11)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('OpenIdMap', 0, 1);

## postgres
# OpenIdMap
CREATE TABLE DB_TABLE_PREFIXOpenIdMap(
 DB_COLUMN_PREFIXopenId VARCHAR(128),
 DB_COLUMN_PREFIXgalleryId INTEGER);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('OpenIdMap', 0, 1);

## oracle
# OpenIdMap
CREATE TABLE DB_TABLE_PREFIXOpenIdMap(
 DB_COLUMN_PREFIXopenId VARCHAR2(128),
 DB_COLUMN_PREFIXgalleryId INTEGER);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('OpenIdMap', 0, 1);

## db2
# OpenIdMap
CREATE TABLE DB_TABLE_PREFIXOpenIdMap(
 DB_COLUMN_PREFIXopenId VARCHAR(128),
 DB_COLUMN_PREFIXgalleryId INTEGER);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('OpenIdMap', 0, 1);

## mssql
# OpenIdMap
CREATE TABLE DB_TABLE_PREFIXOpenIdMap(
 DB_COLUMN_PREFIXopenId NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXgalleryId INT NULL);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('OpenIdMap', 0, 1);

