## mysql
# AddviaemailMap
CREATE TABLE DB_TABLE_PREFIXAddviaemailMap(
 DB_COLUMN_PREFIXitemId int(11) NOT NULL,
 DB_COLUMN_PREFIXitemValue varchar(128),
 DB_COLUMN_PREFIXmode varchar(32),
 DB_COLUMN_PREFIXserverType varchar(128),
 DB_COLUMN_PREFIXserverAddress varchar(128),
 DB_COLUMN_PREFIXusername varchar(128),
 DB_COLUMN_PREFIXpassword varchar(128),
 DB_COLUMN_PREFIXsubjectToMatch varchar(128),
 DB_COLUMN_PREFIXtmpLocation varchar(128),
 DB_COLUMN_PREFIXdeleteProcessed varchar(32),
 DB_COLUMN_PREFIXdestinationAlbum varchar(128),
 PRIMARY KEY(DB_COLUMN_PREFIXitemId)
) TYPE=DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('AddviaemailMap', 1, 0);

## postgres
# AddviaemailMap
CREATE TABLE DB_TABLE_PREFIXAddviaemailMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemValue VARCHAR(128),
 DB_COLUMN_PREFIXmode VARCHAR(32),
 DB_COLUMN_PREFIXserverType VARCHAR(128),
 DB_COLUMN_PREFIXserverAddress VARCHAR(128),
 DB_COLUMN_PREFIXusername VARCHAR(128),
 DB_COLUMN_PREFIXpassword VARCHAR(128),
 DB_COLUMN_PREFIXsubjectToMatch VARCHAR(128),
 DB_COLUMN_PREFIXtmpLocation VARCHAR(128),
 DB_COLUMN_PREFIXdeleteProcessed VARCHAR(32),
 DB_COLUMN_PREFIXdestinationAlbum VARCHAR(128)
);

ALTER TABLE DB_TABLE_PREFIXAddviaemailMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('AddviaemailMap', 1, 0);

## oracle
# AddviaemailMap
CREATE TABLE DB_TABLE_PREFIXAddviaemailMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemValue VARCHAR2(128),
 DB_COLUMN_PREFIXmode VARCHAR2(32),
 DB_COLUMN_PREFIXserverType VARCHAR2(128),
 DB_COLUMN_PREFIXserverAddress VARCHAR2(128),
 DB_COLUMN_PREFIXusername VARCHAR2(128),
 DB_COLUMN_PREFIXpassword VARCHAR2(128),
 DB_COLUMN_PREFIXsubjectToMatch VARCHAR2(128),
 DB_COLUMN_PREFIXtmpLocation VARCHAR2(128),
 DB_COLUMN_PREFIXdeleteProcessed VARCHAR2(32),
 DB_COLUMN_PREFIXdestinationAlbum VARCHAR2(128)
);

ALTER TABLE DB_TABLE_PREFIXAddviaemailMap
 ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('AddviaemailMap', 1, 0);

## db2
# AddviaemailMap
CREATE TABLE DB_TABLE_PREFIXAddviaemailMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemValue VARCHAR(128),
 DB_COLUMN_PREFIXmode VARCHAR(32),
 DB_COLUMN_PREFIXserverType VARCHAR(128),
 DB_COLUMN_PREFIXserverAddress VARCHAR(128),
 DB_COLUMN_PREFIXusername VARCHAR(128),
 DB_COLUMN_PREFIXpassword VARCHAR(128),
 DB_COLUMN_PREFIXsubjectToMatch VARCHAR(128),
 DB_COLUMN_PREFIXtmpLocation VARCHAR(128),
 DB_COLUMN_PREFIXdeleteProcessed VARCHAR(32),
 DB_COLUMN_PREFIXdestinationAlbum VARCHAR(128)
);

ALTER TABLE DB_TABLE_PREFIXAddviaemailMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('AddviaemailMap', 1, 0);

## mssql
# AddviaemailMap
CREATE TABLE DB_TABLE_PREFIXAddviaemailMap(
 DB_COLUMN_PREFIXitemId INT NOT NULL,
 DB_COLUMN_PREFIXitemValue NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXmode NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXserverType NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXserverAddress NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXusername NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXpassword NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXsubjectToMatch NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXtmpLocation NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXdeleteProcessed NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXdestinationAlbum NVARCHAR(128) NULL
);

ALTER TABLE DB_TABLE_PREFIXAddviaemailMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('AddviaemailMap', 1, 0);

