## mysql
# ModerateMap
CREATE TABLE DB_TABLE_PREFIXModerateMap(
 DB_COLUMN_PREFIXitemId int(11) NOT NULL,
 DB_COLUMN_PREFIXownerId int(11) NOT NULL,
 PRIMARY KEY(DB_COLUMN_PREFIXitemId)
) TYPE=DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ModerateMap', 1, 0);

## postgres
# ModerateMap
CREATE TABLE DB_TABLE_PREFIXModerateMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXownerId INTEGER NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXModerateMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ModerateMap', 1, 0);

## oracle
# ModerateMap
CREATE TABLE DB_TABLE_PREFIXModerateMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXownerId INTEGER NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXModerateMap
 ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ModerateMap', 1, 0);

## db2
# ModerateMap
CREATE TABLE DB_TABLE_PREFIXModerateMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXownerId INTEGER NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXModerateMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ModerateMap', 1, 0);

## mssql
# ModerateMap
CREATE TABLE DB_TABLE_PREFIXModerateMap(
 DB_COLUMN_PREFIXitemId INT NOT NULL,
 DB_COLUMN_PREFIXownerId INT NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXModerateMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ModerateMap', 1, 0);

